### ISSUE TITLE
Is it possible to SPECIFY a background color for any usage of initials?

### ISSUE THREAD

**Issue by rstudner** [Exelord/ember-initials#23]
I want to be able to set the background color based on business logic.  Any way to manually control this?

**Comment by rstudner** [comment]
Yeah, it did.  Sorry for the dumb "question on issues then close".

I hadn't cracked open the source code when I wrote it (tsk tsk!) to see backgroundColor as a computed that I could happily clobber for my own purposes  (and backgroundColor isn't mentioned int he docs, but quite possibly it doesn't need to be).

**Comment by Exelord** [comment]
Don't worry. Questions are welcome. :) I just wanted to be sure that you solve it and help others in future adding the correct example. 
But your comment is a great explanation where they can find it. Thanks!
