### ISSUE TITLE
Seeing 404's for image blobs, can't figure out why -- in Chrome, not Firefox *hrmph*

### ISSUE THREAD

**Issue by rstudner** [Exelord/ember-initials#29]
So if I navigate to a certain route in my application, /activity say, I have an ember light table with a cell component that renders some ember-initials (3 of them, 1 per row, and I see 3 console outputs of User's).

<img width="1230" alt="screen shot 2017-04-25 at 3 43 14 pm" src="https://cloud.githubusercontent.com/assets/209970/25404433/ef998e08-29cd-11e7-8317-4b43bd89f782.png">

All is well.

If I navigate away from the route and back, the table looks great, but I now see 
<img width="1223" alt="screen shot 2017-04-25 at 3 41 13 pm" src="https://cloud.githubusercontent.com/assets/209970/25404372/a7e70400-29cd-11e7-962f-5dec241c5818.png">

Which now shows 6 of them.. and then 3 blob errors.

The template has
```
{{#if user.isFulfilled}}
  <div class="user-badge">
    {{#ember-initials
        fontFamily="Yantramanav, Helvetica Neue, Helvetica, Arial, sans-serif"
        name=user.displayName
        seedText=user.email
        backgroundColor=computedBackgroundColor
        size=36}}
      {{#bs-tooltip}}{{user.displayName}}{{/bs-tooltip}}
    {{/ember-initials}}
  </div>
{{/if}}
```

The if statement has been my latest attempt to stop the problem -- but it doesn't work.

**Comment by Exelord** [comment]
Hi, @rstudner 
What version are you using?
Are the errors only in the console or the avatars stop displaying correctly?

I will look at it.

**Comment by rstudner** [comment]
Avatars always display correctly / errors are only in the console.

**Comment by Exelord** [comment]
OK, so what version are you using?
Could you confirm if that issue exists even without `{{#bs-tooltip}}{{user.displayName}}{{/bs-tooltip}}`?

**Comment by rstudner** [comment]
I'm using 3.1.0.

Removing the tooltip doesn't change the console errors.

Side note of interest:  if on this route i'm doing this, I do a full page refresh -- I don't see the errors.
If, I navigate TO the route (from another route), I see the errors.

Hrm.

**Comment by Exelord** [comment]
I was trying to replicate that but I was not able :/ Could you please prepare an [Ember Twiddle](https://ember-twiddle.com) with the bug?
...The priority of the bug is not too high, so is more like "if you would like to prepare..." :)

**Comment by Exelord** [comment]
@rstudner Try the new version v3.2.0 :)
