### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by fredguth** [Exelord/ember-initials#32]
Using ember 2.13.

Did `ember install ember-initials`.
Installed, I checked the node_modules, it is there:

Added this to a template:
```{{ember-initials name="John Doe"}}```

restarted `ember s`

In the template I get the following error:
`Assertion Failed: A helper named \"ember-initials\" could not be found"`

**Comment by fredguth** [comment]
I think the problem is that I use pod structure.

I solved my problem by creating a component and extending the addon:
`import Ember from 'ember';
import EmberInitials from 'ember-initials/components/initials'

export default EmberInitials.extend({
});`

**Comment by Exelord** [comment]
Exactly! :)
