### ISSUE TITLE
how to generate round avatar

### ISSUE THREAD

**Issue by syedasadhasan** [Exelord/ember-initials#38]
I used code as given for round avatar in Live Examples but it is displaying a square one.
What code will generate round one?

**Comment by Exelord** [comment]
You have to style it by yourself. I'm using bootstrap class in the demo: `img-circle`

**Comment by syedasadhasan** [comment]
But the question is how to apply a css class to ember-initial component.

**Comment by Exelord** [comment]
Like to every normal component :)
`{{ember-initials class="my-awesome-class"}}` That's it :)

https://github.com/Exelord/ember-initials/blob/master/tests/dummy/app/components/avatar-initials/template.hbs#L107

**Comment by syedasadhasan** [comment]
Got it. Thank you so much.
