### ISSUE TITLE
Newest release fails in fastboot

### ISSUE THREAD

**Issue by mazondo** [Exelord/ember-initials#42]
Newest release fails with fastboot.

Ember 3.17

error:
```
Error: Cannot find module 'object-hash'
```

Only fails in production, which is delightful :joy:

**Comment by mazondo** [comment]
Took a stab at a fix while also slimming down the library quite a bit here: https://github.com/Exelord/ember-initials/pull/43

**Comment by Exelord** [comment]
Can you give me some intro how to reproduce it in demo app? On my local machine, development and production envs work ok.

**Comment by Exelord** [comment]
@mazondo can please check out v3.6.1 ? I hope it will fix the problem with fastboot initializer stuff

**Comment by Exelord** [comment]
No further issue reports. Feel free to open.
