### ISSUE TITLE
md5 issue with fresh install

### ISSUE THREAD

**Issue by adambedford** [Exelord/ember-initials#56]
I've just installed this addon into an application and am running into the following issue:

```
Error: ENOENT: no such file or directory, open '/Users/adam/Projects/jobtrack/frontend/tmp/source_map_concat-input_base_path-JL9luqlV.tmp/node_modules/blueimp-md5/js/md5.js
```

I saw #25 but it didn't seem to have a resolution for a fresh install. `ember generate ember-initials` throws an Unkown blueprint error.

Any idea how to solve for this? I'm using v3.11

**Comment by Exelord** [comment]
Yep :) ember-md5 is outdated and will be probably deprecated. I will fix this dependency right away!
