### ISSUE TITLE
Receiving ember initials test failures after latest changes to fakerjs package

### ISSUE THREAD

**Issue by yortz** [Exelord/ember-initials#75]
Please ignore this or feel free to flag it as close in case you would find it redundant or not related to this particular repo, I am deciding anyway to document this issue in case this could save some time and avoid frustration to other people. We just started receiving several failures while running our test suite for our application either locally or on heroku CI. We did not released any new feature and we were totally lost and going nuts in trying to understand what was causing the failure, since this just happened out of the blue and at first sight this seemed to be related to `ember-initials` (below is the error message we were getting)

```
Uncaught Error: Assertion Failed: Cannot modify dependent keys for `seedText` on `<application-name@component:ember-initials::ember602>` after it has been destroyed.
```

After spending some time on this, we found out that in one of our fixtures we were using faker to randomly generate thumbnails when running tests

```
  avatar: {
    original: faker.image.avatar(),
    medium: faker.image.avatar(),
    icon: faker.image.avatar()
  }
 ```

and the latest changes to the `fakerjs` package were completely crashing our tests, this due to the fact that one of the maintainer decided to make the entire S3 folder private as documented here

https://github.com/Marak/faker.js/issues/1055

The fix for this, at least for us, was not to rely anymore on `fakerjs` to generate the avatar when running our tests, hope this could help some other people...

**Comment by Exelord** [comment]
I would advise stopping using faker and test on repeatable data :) Faker brings randomness to the tests which causes more bad than good as well as it makes the tests not deterministic, running them constantly on different sets of data.
